author: Rithvik Kashyap
description:  Website about Rithvik
url:  https://Rithvik.Kashyap.one
email: Rithvik [at] Kashyap.one
title:  Welcome to my website

theme: minima



header_pages:
  - _pages/homepage.md
#  - _pages/about.md
 

include:
    - _pages
    
    
 


plugins:
 - jekyll-feed
 - jekyll-seo-tag
