author: Rithvik Kashyap
description:  
url:  https://Rithvik.Kashyap.one
email: Rithvik [at] Kashyap.one
title:  

theme: minima



header_pages:
  - _pages/homepage.md
  - _pages/about.md
 

include:
    - _pages
    
    
base-url: /about.md


plugins:
 - jekyll-feed
 - jekyll-seo-tag
